#include "types-win32.h"
//----- (10038510) --------------------------------------------------------
int __cdecl ParseTrackHeader(unk00230 *outBuffer, CHK_File *fp) {
    int v3;               // ecx MAPDST
    int v4;               // eax MAPDST
    int v5;               // edx MAPDST
    char *v6;             // eax MAPDST
    unsigned __int16 v11; // dx MAPDST
    unk00230 *Buffera;    // [esp+50h] [ebp+4h]
    int fpa;              // [esp+54h] [ebp+8h]

    CHK_FReadReportError(outBuffer, 1u, 0x230u, fp);
    LOBYTE(v3) = BYTE1(outBuffer->field_0);
    BYTE1(v3) = outBuffer->field_0;
    outBuffer->field_0 = HIBYTE(outBuffer->field_0) |
                         ((BYTE2(outBuffer->field_0) | ((unsigned __int16)v3 << 8)) << 8);
    LOBYTE(v3) = BYTE1(outBuffer->field_4);
    BYTE1(v3) = outBuffer->field_4;
    outBuffer->field_4 = HIBYTE(outBuffer->field_4) |
                         ((BYTE2(outBuffer->field_4) | ((unsigned __int16)v3 << 8)) << 8);
    LOBYTE(v3) = BYTE1(outBuffer->field_8);
    BYTE1(v3) = outBuffer->field_8;
    outBuffer->field_8 = HIBYTE(outBuffer->field_8) |
                         ((BYTE2(outBuffer->field_8) | ((unsigned __int16)v3 << 8)) << 8);
    LOBYTE(v3) = HIBYTE(outBuffer->field_C);
    Buffera = (unk00230 *)&outBuffer->field_C;
    HIBYTE(outBuffer->field_C) = outBuffer->field_C;
    LOBYTE(outBuffer->field_C) = v3;
    LOBYTE(v4) = BYTE2(outBuffer->field_C);
    BYTE2(outBuffer->field_C) = BYTE1(outBuffer->field_C);
    BYTE1(outBuffer->field_C) = v4;
    LOBYTE(v5) = BYTE1(outBuffer->field_10);
    BYTE1(v5) = outBuffer->field_10;
    outBuffer->field_10 = HIBYTE(outBuffer->field_10) |
                          ((BYTE2(outBuffer->field_10) | ((unsigned __int16)v5 << 8)) << 8);
    LOBYTE(v3) = HIBYTE(outBuffer->field_14);
    HIBYTE(outBuffer->field_14) = outBuffer->field_14;
    LOBYTE(outBuffer->field_14) = v3;
    LOBYTE(v4) = BYTE2(outBuffer->field_14);
    BYTE2(outBuffer->field_14) = BYTE1(outBuffer->field_14);
    BYTE1(outBuffer->field_14) = v4;
    LOBYTE(v5) = BYTE1(outBuffer->field_18);
    BYTE1(v5) = outBuffer->field_18;
    outBuffer->field_18 = HIBYTE(outBuffer->field_18) |
                          ((BYTE2(outBuffer->field_18) | ((unsigned __int16)v5 << 8)) << 8);
    LOBYTE(v3) = HIBYTE(outBuffer->field_1C);
    HIBYTE(outBuffer->field_1C) = outBuffer->field_1C;
    LOBYTE(outBuffer->field_1C) = v3;
    LOBYTE(v4) = BYTE2(outBuffer->field_1C);
    BYTE2(outBuffer->field_1C) = BYTE1(outBuffer->field_1C);
    BYTE1(outBuffer->field_1C) = v4;
    LOBYTE(v3) = HIBYTE(outBuffer->field_20);
    HIBYTE(outBuffer->field_20) = outBuffer->field_20;
    LOBYTE(outBuffer->field_20) = v3;
    LOBYTE(v4) = BYTE2(outBuffer->field_20);
    BYTE2(outBuffer->field_20) = BYTE1(outBuffer->field_20);
    BYTE1(outBuffer->field_20) = v4;
    LOBYTE(v3) = HIBYTE(outBuffer->field_24);
    HIBYTE(outBuffer->field_24) = outBuffer->field_24;
    LOBYTE(outBuffer->field_24) = v3;
    LOBYTE(v4) = BYTE2(outBuffer->field_24);
    BYTE2(outBuffer->field_24) = BYTE1(outBuffer->field_24);
    BYTE1(outBuffer->field_24) = v4;
    LOBYTE(v4) = HIBYTE(outBuffer->field_28);
    HIBYTE(outBuffer->field_28) = outBuffer->field_28;
    LOBYTE(outBuffer->field_28) = v4;
    LOBYTE(v4) = BYTE2(outBuffer->field_28);
    BYTE2(outBuffer->field_28) = BYTE1(outBuffer->field_28);
    BYTE1(outBuffer->field_28) = v4;
    LOBYTE(v4) = HIBYTE(outBuffer->field_2C);
    HIBYTE(outBuffer->field_2C) = outBuffer->field_2C;
    LOBYTE(outBuffer->field_2C) = v4;
    LOBYTE(v4) = BYTE2(outBuffer->field_2C);
    BYTE2(outBuffer->field_2C) = BYTE1(outBuffer->field_2C);
    BYTE1(outBuffer->field_2C) = v4;
    LOBYTE(v4) = HIBYTE(outBuffer->field_30);
    HIBYTE(outBuffer->field_30) = outBuffer->field_30;
    LOBYTE(outBuffer->field_30) = v4;
    LOBYTE(v4) = BYTE2(outBuffer->field_30);
    BYTE2(outBuffer->field_30) = BYTE1(outBuffer->field_30);
    BYTE1(outBuffer->field_30) = v4;
    LOBYTE(v4) = HIBYTE(outBuffer->field_34);
    HIBYTE(outBuffer->field_34) = outBuffer->field_34;
    LOBYTE(outBuffer->field_34) = v4;
    LOBYTE(v4) = BYTE2(outBuffer->field_34);
    BYTE2(outBuffer->field_34) = BYTE1(outBuffer->field_34);
    BYTE1(outBuffer->field_34) = v4;
    LOBYTE(v4) = HIBYTE(outBuffer->field_38);
    HIBYTE(outBuffer->field_38) = outBuffer->field_38;
    LOBYTE(outBuffer->field_38) = v4;
    LOBYTE(v4) = BYTE2(outBuffer->field_38);
    BYTE2(outBuffer->field_38) = BYTE1(outBuffer->field_38);
    BYTE1(outBuffer->field_38) = v4;
    LOBYTE(v4) = HIBYTE(outBuffer->field_3C);
    HIBYTE(outBuffer->field_3C) = outBuffer->field_3C;
    LOBYTE(outBuffer->field_3C) = v4;
    LOBYTE(v4) = BYTE2(outBuffer->field_3C);
    BYTE2(outBuffer->field_3C) = BYTE1(outBuffer->field_3C);
    BYTE1(outBuffer->field_3C) = v4;
    v6 = outBuffer->field_40;
    v3 = 4;
    do {
        LOBYTE(v5) = v6[3];
        v6[3] = *v6;
        *v6 = v5;
        LOBYTE(v5) = v6[2];
        v6[2] = v6[1];
        v6[1] = v5;
        v6 += 4;
        --v3;
    } while (v3);
    LOBYTE(v4) = HIBYTE(outBuffer->field_50);
    HIBYTE(outBuffer->field_50) = outBuffer->field_50;
    LOBYTE(outBuffer->field_50) = v4;
    LOBYTE(v4) = BYTE2(outBuffer->field_50);
    BYTE2(outBuffer->field_50) = BYTE1(outBuffer->field_50);
    BYTE1(outBuffer->field_50) = v4;
    LOBYTE(v4) = HIBYTE(outBuffer->field_54);
    HIBYTE(outBuffer->field_54) = outBuffer->field_54;
    LOBYTE(outBuffer->field_54) = v4;
    LOBYTE(v4) = BYTE2(outBuffer->field_54);
    BYTE2(outBuffer->field_54) = BYTE1(outBuffer->field_54);
    BYTE1(outBuffer->field_54) = v4;
    LOBYTE(v4) = HIBYTE(outBuffer->field_58);
    HIBYTE(outBuffer->field_58) = outBuffer->field_58;
    LOBYTE(outBuffer->field_58) = v4;
    LOBYTE(v4) = BYTE2(outBuffer->field_58);
    BYTE2(outBuffer->field_58) = BYTE1(outBuffer->field_58);
    BYTE1(outBuffer->field_58) = v4;
    v3 = HIBYTE(outBuffer->field_5C);
    HIBYTE(outBuffer->field_5C) = outBuffer->field_5C;
    LOBYTE(outBuffer->field_5C) = v3;
    LOBYTE(v4) = BYTE2(outBuffer->field_5C);
    BYTE2(outBuffer->field_5C) = BYTE1(outBuffer->field_5C);
    BYTE1(outBuffer->field_5C) = v4;
    LOBYTE(v3) = HIBYTE(outBuffer->field_60);
    HIBYTE(outBuffer->field_60) = outBuffer->field_60;
    LOBYTE(outBuffer->field_60) = v3;
    LOBYTE(v4) = BYTE2(outBuffer->field_60);
    BYTE2(outBuffer->field_60) = BYTE1(outBuffer->field_60);
    BYTE1(outBuffer->field_60) = v4;
    LOBYTE(v11) = BYTE1(outBuffer->field_64);
    HIBYTE(v11) = outBuffer->field_64;
    outBuffer->field_64 =
        HIBYTE(outBuffer->field_64) | ((BYTE2(outBuffer->field_64) | (v11 << 8)) << 8);
    LOBYTE(v3) = HIBYTE(outBuffer->field_68);
    HIBYTE(outBuffer->field_68) = outBuffer->field_68;
    LOBYTE(outBuffer->field_68) = v3;
    LOBYTE(v4) = BYTE2(outBuffer->field_68);
    BYTE2(outBuffer->field_68) = BYTE1(outBuffer->field_68);
    BYTE1(outBuffer->field_68) = v4;
    LOBYTE(v3) = HIBYTE(outBuffer->field_6C);
    HIBYTE(outBuffer->field_6C) = outBuffer->field_6C;
    LOBYTE(outBuffer->field_6C) = v3;
    LOBYTE(v4) = BYTE2(outBuffer->field_6C);
    BYTE2(outBuffer->field_6C) = BYTE1(outBuffer->field_6C);
    BYTE1(outBuffer->field_6C) = v4;
    LOBYTE(v3) = HIBYTE(outBuffer->field_70);
    HIBYTE(outBuffer->field_70) = outBuffer->field_70;
    LOBYTE(outBuffer->field_70) = v3;
    LOBYTE(v4) = BYTE2(outBuffer->field_70);
    BYTE2(outBuffer->field_70) = BYTE1(outBuffer->field_70);
    BYTE1(outBuffer->field_70) = v4;
    LOBYTE(v3) = HIBYTE(outBuffer->field_74);
    HIBYTE(outBuffer->field_74) = outBuffer->field_74;
    LOBYTE(outBuffer->field_74) = v3;
    LOBYTE(v4) = BYTE2(outBuffer->field_74);
    BYTE2(outBuffer->field_74) = BYTE1(outBuffer->field_74);
    BYTE1(outBuffer->field_74) = v4;
    LOBYTE(v3) = HIBYTE(outBuffer->field_78);
    HIBYTE(outBuffer->field_78) = outBuffer->field_78;
    LOBYTE(outBuffer->field_78) = v3;
    LOBYTE(v4) = BYTE2(outBuffer->field_78);
    LOBYTE(v11) = BYTE1(outBuffer->field_7C);
    BYTE2(outBuffer->field_78) = BYTE1(outBuffer->field_78);
    HIBYTE(v11) = outBuffer->field_7C;
    BYTE1(outBuffer->field_78) = v4;
    LOBYTE(v3) = HIBYTE(outBuffer->field_84);
    outBuffer->field_7C =
        HIBYTE(outBuffer->field_7C) | ((BYTE2(outBuffer->field_7C) | (v11 << 8)) << 8);
    HIBYTE(outBuffer->field_84) = outBuffer->field_84;
    LOBYTE(outBuffer->field_84) = v3;
    LOBYTE(v3) = BYTE1(outBuffer->field_84);
    LOBYTE(v11) = BYTE1(outBuffer->field_88);
    BYTE1(outBuffer->field_84) = BYTE2(outBuffer->field_84);
    HIBYTE(v11) = outBuffer->field_88;
    v4 = BYTE2(outBuffer->field_88);
    BYTE2(outBuffer->field_84) = v3;
    LOBYTE(v3) = HIBYTE(outBuffer->field_8C);
    outBuffer->field_88 = HIBYTE(outBuffer->field_88) | ((v4 | (v11 << 8)) << 8);
    LOBYTE(v11) = outBuffer->field_8C;
    LOBYTE(outBuffer->field_8C) = v3;
    LOBYTE(v3) = BYTE1(outBuffer->field_8C);
    BYTE1(outBuffer->field_8C) = BYTE2(outBuffer->field_8C);
    BYTE2(outBuffer->field_8C) = v3;
    LOBYTE(v3) = HIBYTE(outBuffer->field_90);
    HIBYTE(outBuffer->field_8C) = v11;
    LOBYTE(v11) = outBuffer->field_90;
    LOBYTE(outBuffer->field_90) = v3;
    LOBYTE(v3) = BYTE1(outBuffer->field_90);
    LOBYTE(v4) = BYTE2(outBuffer->field_90);
    HIBYTE(outBuffer->field_90) = v11;
    BYTE2(outBuffer->field_90) = v3;
    LOBYTE(v3) = HIBYTE(outBuffer->field_94);
    LOBYTE(v11) = outBuffer->field_94;
    BYTE1(outBuffer->field_90) = v4;
    HIBYTE(outBuffer->field_94) = v11;
    LOBYTE(outBuffer->field_94) = v3;
    LOBYTE(v3) = BYTE1(outBuffer->field_94);
    BYTE1(outBuffer->field_94) = BYTE2(outBuffer->field_94);
    BYTE2(outBuffer->field_94) = v3;
    v6 = outBuffer->field_98;
    fpa = 10;
    do {
        LOBYTE(v3) = v6[3];
        v6[3] = *v6;
        *v6 = v3;
        LOBYTE(v3) = v6[2];
        v6[2] = v6[1];
        v6[1] = v3;
        LOBYTE(v3) = v6[7];
        v6[7] = v6[4];
        v6[4] = v3;
        LOBYTE(v3) = v6[6];
        v6[6] = v6[5];
        v6[5] = v3;
        LOBYTE(v3) = v6[11];
        v6[11] = v6[8];
        v6[8] = v3;
        LOBYTE(v3) = v6[10];
        v6[10] = v6[9];
        v6[9] = v3;
        LOBYTE(v3) = v6[15];
        v6[15] = v6[12];
        v6[12] = v3;
        LOBYTE(v3) = v6[14];
        v6[14] = v6[13];
        v6[13] = v3;
        LOBYTE(v3) = v6[19];
        v6[19] = v6[16];
        v6[16] = v3;
        LOBYTE(v3) = v6[18];
        v6[18] = v6[17];
        v6[17] = v3;
        v6 += 20;
        --fpa;
    } while (fpa);
    LOBYTE(v11) = BYTE1(outBuffer->field_160);
    HIBYTE(v11) = outBuffer->field_160;
    outBuffer->field_160 =
        HIBYTE(outBuffer->field_160) | ((BYTE2(outBuffer->field_160) | (v11 << 8)) << 8);
    track_1002B970(&Buffera->field_0);
    track_1002B970(&outBuffer->field_14);
    track_1002B970(&outBuffer->field_1C);
    track_1002B970(&outBuffer->field_20);
    track_1002B970(&outBuffer->field_24);
    track_1002B970(&outBuffer->field_50);
    track_1002B970(&outBuffer->field_54);
    track_1002B970(&outBuffer->field_58);
    track_1002B970(&outBuffer->field_5C);
    track_1002B970(&outBuffer->field_60);
    track_1002B970(&outBuffer->field_68);
    track_1002B970(&outBuffer->field_6C);
    track_1002B970(&outBuffer->field_70);
    track_1002B970(&outBuffer->field_74);
    track_1002B970(&outBuffer->field_78);
    track_1002B970(&outBuffer->field_84);
    track_1002B970(&outBuffer->field_8C);
    track_1002B970(&outBuffer->field_90);
    return track_1002B970(&outBuffer->field_94);
}
